def update_from_datasource(self):
             images = {'images': self.glance.images.list()}
             self._translate_images(images)
         except Exception as e:
             # TODO(zhenzanz): this is a workaround. The glance client should
             # handle 401 error.
             if e.code == 401:
                 keystone = ksclient.Client(**self.creds)
                 self.glance.http_client.auth_token = keystone.auth_token
             else:
                 raise e
 
     @ds_utils.update_state_on_changed(IMAGES)
     def _translate_images(self, obj):
 -- a/congress/datasources/heatv1_driver.py
